/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class feedback {
    constructor() {
        this.id = undefined;
        this.uid = undefined;
        this.advise = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setAdvise(advise) {
        this.advise = advise;
    }

    getAdvise() {
        return this.advise;
    }
}

feedback.className = 'feedback';

export {feedback}