/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class museum {
    constructor() {
        this.id = undefined;
        this.name = undefined;
        this.time = undefined;
        this.creator = undefined;
        this.level = undefined;
        this.placeOfOrigin = undefined;
        this.museum = undefined;
        this.type = undefined;
        this.size = undefined;
        this.material = undefined;
        this.description = undefined;
        this.collectionUrl = undefined;
        this.imageUrl = undefined;
        this.likes = 0;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setTime(time) {
        this.time = time;
    }

    getTime() {
        return this.time;
    }

    setCreator(creator) {
        this.creator = creator;
    }

    getCreator() {
        return this.creator;
    }

    setLevel(level) {
        this.level = level;
    }

    getLevel() {
        return this.level;
    }

    setPlaceOfOrigin(placeOfOrigin) {
        this.placeOfOrigin = placeOfOrigin;
    }

    getPlaceOfOrigin() {
        return this.placeOfOrigin;
    }

    setMuseum(museum) {
        this.museum = museum;
    }

    getMuseum() {
        return this.museum;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setSize(size) {
        this.size = size;
    }

    getSize() {
        return this.size;
    }

    setMaterial(material) {
        this.material = material;
    }

    getMaterial() {
        return this.material;
    }

    setDescription(description) {
        this.description = description;
    }

    getDescription() {
        return this.description;
    }

    setCollectionUrl(collectionUrl) {
        this.collectionUrl = collectionUrl;
    }

    getCollectionUrl() {
        return this.collectionUrl;
    }

    setImageUrl(imageUrl) {
        this.imageUrl = imageUrl;
    }

    getImageUrl() {
        return this.imageUrl;
    }

    setLikes(likes) {
        this.likes = likes;
    }

    getLikes() {
        return this.likes;
    }
}

museum.className = 'museum';

export {museum}