/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class user {
    constructor() {
        this.user_id = undefined;
        this.user_name = undefined;
        this.uid = undefined;
        this.user_photoUrl = undefined;
    }

    setUser_id(user_id) {
        this.user_id = user_id;
    }

    getUser_id() {
        return this.user_id;
    }

    setUser_name(user_name) {
        this.user_name = user_name;
    }

    getUser_name() {
        return this.user_name;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setUser_photoUrl(user_photoUrl) {
        this.user_photoUrl = user_photoUrl;
    }

    getUser_photoUrl() {
        return this.user_photoUrl;
    }
}

user.className = 'user';

export {user}