/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class userLikes {
    constructor() {
        this.like_id = undefined;
        this.id = undefined;
        this.uid = undefined;
    }

    setLike_id(like_id) {
        this.like_id = like_id;
    }

    getLike_id() {
        return this.like_id;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }
}

userLikes.className = 'userLikes';

export {userLikes}