/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class userReview {
    constructor() {
        this.reviewId = undefined;
        this.uid = undefined;
        this.id = undefined;
        this.content = undefined;
        this.imageUrl = undefined;
    }

    setReviewId(reviewId) {
        this.reviewId = reviewId;
    }

    getReviewId() {
        return this.reviewId;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setImageUrl(imageUrl) {
        this.imageUrl = imageUrl;
    }

    getImageUrl() {
        return this.imageUrl;
    }
}

userReview.className = 'userReview';

export {userReview}